### ISSUE TITLE
Code 10003 when delete ticket

### ISSUE THREAD

**Issue by TylerNe** [apidev234/ButtonTickets#1]
Hi, I am Tyler

 The bot have a erro when i try to delete the ticket. After the ticket was deleted, the consol will send the erro with message
 DiscordAPIError: Unknown Channel
code: 10003,
  httpStatus: 404

**Comment by gaurishhs** [comment]
Hello, Please Re-Clone This Repo,

There was a Glitch,

i Basically Forgot to Await The Delete Channel Method,
Reference For Await/Async: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

This Issue has Been Resolved,

If You Still Face The Problem, You May Open a new issue.
