### ISSUE TITLE
Still same erro

### ISSUE THREAD

**Issue by TylerNe** [apidev234/ButtonTickets#2]
Hi, I am Tyler

 The bot have a erro when i try to delete the ticket. After the ticket was deleted, the consol will send the erro with message
 DiscordAPIError: Unknown Channel
code: 10003,
  httpStatus: 404

**Comment by gaurishhs** [comment]
The Code has been updated,

Try re-cloning the repository.

Learn Git Clone: https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository
Learn Git Pull: https://github.com/git-guides/git-pull
